language: node_js
node_js:
  - "8.1.3"

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # `-> to be able to launch Firefox through Karma

script:
  - grunt test

after_success:
  - grunt coveralls
